
name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Your generated configuration will be inserted below
      - name: Fetch secrets from vault
        id: fetch-secrets
        uses: EntrustCorporation/secrets-vault-action@v1
        with:
          base_url: https://10.1.228.68/
          auth_type: 'userpass'
          username: "vaultadmin@entrust.com"
          password: "Hytrust123!"
          vault_uid: "d79fccbe-1c33-409b-9089-46b96c8694d5"
          ca_cert: "" 
          secrets: |
            BOX.DOCKER_USERNAME | DOCKER_USERNAME;
            BOX.DOCKER_PASSWORD | DOCKER_PASSWORD;


      # Example of how to use the fetched secrets
      - name: Use secrets
        run: |
          echo "Using secrets in your workflow"
          # Access as environment variables
          echo "Running with API from $DOCKER_USERNAME"
          
          # Or access as outputs
          echo "API Key is masked: ${{ steps.fetch-secrets.outputs.DOCKER_PASSWORD }}"
