
name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Your generated configuration will be inserted below
      - name: Fetch secrets from vault
        id: fetch-secrets
        uses: EntrustCorporation/secrets-vault-action@v1
        with:
          base_url: https://34.224.87.212/
          auth_type: 'userpass'
          username: ${{secrets.VAULT_USERNAME}}
          password: ${{secrets.VAULT_PASSWORD}}
          vault_uid: ${{secrets.VAULT_UID}}
          ca_cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGeHpDQ0E2K2dBd0lCQWdJVUU5ei9IMVo4YVVDbEthenFOWmZmYXVHSHVkc3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3Y3pFTE1Ba0dBMVVFQmhNQ2FXNHhDekFKQmdOVkJBZ01BbTFvTVFzd0NRWURWUVFIREFKcllURUxNQWtHDQpBMVVFQ2d3Q2Qya3hDekFKQmdOVkJBc01BbVZ1TVE0d0RBWURWUVFEREFWaGNtbG1ZVEVnTUI0R0NTcUdTSWIzDQpEUUVKQVJZUllYSnBabUZBWlc1MGNuVnpkQzVqYjIwd0hoY05NalV3T0RFNU1EY3dOVEUxV2hjTk16VXdPREUzDQpNRGN3TlRFMVdqQnpNUXN3Q1FZRFZRUUdFd0pwYmpFTE1Ba0dBMVVFQ0F3Q2JXZ3hDekFKQmdOVkJBY01BbXRoDQpNUXN3Q1FZRFZRUUtEQUozYVRFTE1Ba0dBMVVFQ3d3Q1pXNHhEakFNQmdOVkJBTU1CV0Z5YVdaaE1TQXdIZ1lKDQpLb1pJaHZjTkFRa0JGaEZoY21sbVlVQmxiblJ5ZFhOMExtTnZiVENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEDQpnZ0lQQURDQ0Fnb0NnZ0lCQUlLUE9wc09oNVZvakZlYU0rTko3Z0F5SCtGaVYyYUhPeTRXaTN4NExKbVdnVi9IDQoxL0VWc0lXTzBVa1BsanJBODQ5S2NmMU50T2piUHVKekJHQ2EyZjlWcHE3QjVBV082Z0R6OTFhd3hWSTFFNmc0DQozc3NwODdiY2c4MkltZDZSV1FOLzgrSlBXcE5CUGx1b1ViR3REbnJ4L3MvMjc1cWF4ck1zSXJ0cHhORWhlRG1TDQpmMXNjbTJIRWNqUWFiMDIwbDBlMW9NWThwcHJJcUdCUi9nTFZVU213dlI4RHhQWjgrOFMwVk9sd1JWT0NyeVBIDQp1YVl5RGtaS1FxSVVGWnRBVkxScnBwQWJLMkhXb2U3Rm1FSlMxTER1cFRDV3JoenZoSGxpSlZFa3JLL3cyckpQDQpOWHBLUE1zMXlvcUJ5RGIvcldJVUhvRG9JUUhyTHRqb002UTBwcFY4aE1lMG1NTklDeEhMLy9UUG1Pbm4vVTAyDQpYL2MyV0lteDg0WGphVWNYYW1tY3V5Vno0a3BsZkp2NXRjMXc1WVY2THpXamlsbVM0MkU0QUxlNUJLVWZQZSszDQpjeEtaQUh6TUZkWkUycW1ndVN2a2NTQ1ZZaGtXZVR1eGlMdkZpa2s3c3BUVEJodUFmd2wxYjNJRlkvdmFFY0NoDQo2SFZNMUVTSlNicGpGeTBjRVMxVXBQUXJweWxTWnNiR3RTSWV2VDRtcnlnK1JwRnBhOTFaOWswVDRvS1pYekpuDQpEc3B3ZW9PUU9zQnRQb3RKK0hvdXo0V3R0eG56TEU5a3RZSG92Q244REFWMStTRlBqRmc1TkszblVwVjhaeEFCDQpPOTl6UC9XckVmOGh5dFVNenduZ3dlS1dEL0c0TFk2VS9ucFl2bm56dnZRMXQycWF2RUhPRUM2TkEyUTdBZ01CDQpBQUdqVXpCUk1CMEdBMVVkRGdRV0JCUjcyNCtxdTZ0eTM2QlRzYXcxUytYeTExV1N2akFmQmdOVkhTTUVHREFXDQpnQlI3MjQrcXU2dHkzNkJUc2F3MVMrWHkxMVdTdmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzDQpEUUVCQ3dVQUE0SUNBUUJZbkZRNGNHNlRDRkZERkYxNjlQd2kwRlZFZStyL2ZCdkRvLys3Q2FteEh2OXJWclBQDQpaNHQzU091L09DWlhtcTRHWFB0OEpmLzBCWnYvQlVJdWFhbU1qd0lqVUh6QTNack1OdXJjbTFUQUJCeVhMK0UwDQp3dUk1OUViaFRyRm9tYTltUnhvSUQxOTFWVnlQS1JuQnBaQ3RrLzd1Y3BuTmZac0dmNGNwY3dnNmVDWWRpVjlvDQpKUHpxT0NjRjQybmd5Mk1MSWE4K1hudWxodTY5YjNHZnhMODZGaUJaNEViOXFpMDNxUzR5Rk94NDI0VWZ0ZGpMDQpWT2NxMzVzYUpraHczb1NxTlBFOWxqWE4za05MMmU2VUE0a2JrWm05UEl2UDM2bGhJcUV5aWZWSU41Ui9JdVRTDQpSa00xNW53Z0hXbUFQclhFTXlFc29QMTdYOVI5SDF2eUZvWFpCQmU5YTNtRU1PRDBBV3lFUmwxV2Q4L2lsUDNPDQpsVE1xRndUd3BhdFBJY0JkVGVOcmRvT1NRZWVyNEhhWERrbnQ5ODlTVllRdFBkVjN5ZEZuS2dtdGlyMldFYS8wDQp0eWpXNEtPR09LRU1BVC9GR2FwMVM1SDZjRFpqZHcxVXZWT2dHbG1hR1NYUHBCMmF0OTB0QzQwR3Jhcjg0cDNaDQpobzBHSFNqb2grdnNvc3pBTlBGbVZ4SkRzN1FXWlgzMHpKMmNocTdwN1RTc2N3dFRESHkzeDF6SGxKNG9VaDBtDQpERk85ZnRYRzNZbEdpbUgvak13Q0Njc29iQS9yeGdXZVdPcmxmNDdzM0tkSFpUTU1rdjI2VVJOQ3k0Rkt5dWhRDQpWb1ptc2RaR1JPdi8rRkVuQVNvVXhRV2h4b041UnMwZ3RqQ2wvd2VEdmt0dEVUL09rMldJMHBYcXN3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=" # Auto-converted from ca.crt.pem
          secrets: |
            Box.username | username;
            Box.password | password;

            


      # Example of how to use the fetched secrets
      - name: Use secrets
        run: |
          echo "Using secrets in your workflow"
          # Access as environment variables
          echo "Running with API from $username"
          
          # Or access as outputs
          echo "API Key is masked: ${{ steps.fetch-secrets.outputs.password }}"
