
name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Your generated configuration will be inserted below
      - name: Fetch secrets from vault
        id: fetch-secrets
        uses: EntrustCorporation/secrets-vault-action@v1
        with:
          base_url: https://13.222.5.79/
          auth_type: 'userpass'
          username: ${{secrets.VAULT_USERNAME}}
          password: ${{secrets.VAULT_PASSWORD}}
          vault_uid: ${{secrets.VAULT_UID}}
          ca_cert: "" 
          secrets: |
            box.password_secret | password_secret;
            


      # Example of how to use the fetched secrets
      - name: Use secrets
        run: |
          echo "Using secrets in your workflow"
          # Access as environment variables
          echo "Running with API from $DOCKER_USERNAME"
          
          # Or access as outputs
          echo "API Key is masked: ${{ steps.fetch-secrets.outputs.DOCKER_PASSWORD }}"
